global.d.ts
# Configuração do Prometheus para monitoramento do QuickAssetsGlobal

# Configuração global
global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Configuração de alertas
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Regras de alerta
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# Configuração de scraping
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'backend'
    static_configs:
      - targets: ['backend:3000']

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']

  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
